# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            阿毛的蛋疼地
description:      '阿毛的蛋疼地'
baseurl:          'http://xiangwangfeng.github.io/'
paginate:         15

author:
  name:           'Xiang Wangfeng'
  url:            xiangwangfeng.com

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/xiangwangfeng/xiangwangfeng.github.io
