# Dependencies
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
pygments:         true

# Permalinks
permalink: /:year-:month-:day-:title/

gems: [jekyll-paginate]

# Setup
title:            阿毛的蛋疼地
description:      '阿毛的蛋疼地'
paginate:         12

author:
  name:           'Xiang Wangfeng'
  url:            xiangwangfeng.com

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/xiangwangfeng/xiangwangfeng.github.io
