# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            阿毛的蛋疼地
tagline:          ''
baseurl:          '/'
paginate:         5

author:
  name:           'Xiang Wangfeng'
  url:            xiangwangfeng.com

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/xiangwangfeng/xiangwangfeng.github.io
